enum HermesTitle
{
    // ERRO
    CRITICAL_ERROR =  "ERRO CRÍTICO",

    // AVISO
    NEW_CHAT = "NOVO CHAT NO BOARD",
    NEW_LIKE = "NOVO LIKE NO POST",
    NEW_COMMENT = "NOVO COMENTÁRIO NO POST",
    EMAIL_APPROVED = "EMAIL APROVADO",

    // REGISTRO
    NEW_USER = "NOVO USUÁRIO NO SISTEMA",
    TRACE_ACTION = "REGISTRO DE AÇÃO DE USUÁRIO",

    // DEMANDA AÇÃO
    USER_APPROVATION = "USUÁRIO NOVO A APROVAR",
    EMAIL_APPROVAL_REQUEST = "APROVAÇÃO DE EMAIL",
}

export default HermesTitle
